# Generated by Django 3.2.13 on 2022-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=3)),
                ('todo', models.CharField(max_length=80)),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
